1746632175450	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1746632585765	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1746632585765	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1746632585774	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1746632585782	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1746632585794	Sync.SyncScheduler	DEBUG	Woke from sleep.
1746632585794	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1746632585795	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1746632585800	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1746632587800	Sync.Service	DEBUG	User-Agent: Zen/1.12b (Linux x86_64) FxSync/1.140.0.20250502094717.desktop
1746632587800	Sync.Service	INFO	Starting sync at 2025-05-07 12:43:07 in browser session uEOodoPTH525
1746632587804	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1746632587805	Sync.Status	INFO	Resetting Status.
1746632587805	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1746632587806	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1746632587806	FirefoxAccounts	DEBUG	getOAuthToken enter
1746632587806	FirefoxAccounts	TRACE	getCachedToken returning cached token
1746632587806	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1746632587807	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1746632587813	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1746632587813	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1746632587814	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/263665549/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1746632587814	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1746632587814	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1746632587816	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1746632587816	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1746632587818	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
